package com.nimel.mymicroservices.beerorderservice.entity;

public enum OrderStatusEnum {
	NEW, 
	VALIDATED, 
	VALIDATION_EXCEPTION,
	ALLOCATED,
	ALLOCATION_ERROR,
	PENDING_INVENTORY,
	DELIVERED,
	DELIVERY_EXCEPTION,
	CANCELLED,
	
	
	READY,
	PICKED_UP, PENDING_VALIDATION, PENDING_ALLOCATION
}
